version: "3.9"

services:                 # expose REST API
  api:
    build: .
    container_name: ocean-sense-api
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./datasets:/app/datasets        # hot-load new csv files
      - ./chroma_store:/app/chroma_store

    restart: unless-stopped

